language: node_js
node_js:
  - "0.11"
  - "0.10"
before_install:
  - "npm install -g grunt"
  - "npm install -g grunt-cli"
install:
  - "npm install"
before_script:
  - "npm install cordova -g"
script:
  - "grunt 'clean files'"
  - "grunt 'phonegap_project:create'"
  - "grunt 'phonegap_project:build'"