language: node_js
node_js:
  - "6"
  - "5"
  - "4"
before_install:
  - npm install -g cordova
  - npm install -g grunt
  - npm install -g grunt-cli
install:
  - npm install
# before_script:
script:
  - grunt
  #- "grunt 'clean files'"
  #- "grunt 'phonegap_project:create'"
  #- "grunt 'phonegap_project:build'"